routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProdusenDataController;
use App\Http\Controllers\LandingPageController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\MasterDataKinerja\PerformanceController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\ActivityController;
use App\Http\Controllers\Admin\EmailSettingController;
use App\Http\Controllers\Admin\TelegramSettingController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\UnitKerja\CategoryController;
use App\Http\Controllers\UnitKerja\WorkUnitController;
use App\Http\Controllers\UnitKerja\KinerjaController;
use App\Http\Controllers\UnitKerja\KotakMasukController;
use App\Http\Controllers\UnitKerja\ChatController;
use App\Http\Controllers\Informasi\InfografisController;
use App\Http\Controllers\Informasi\NewsController;
use App\Http\Controllers\UnitKerja\ChartController;
use App\Http\Controllers\Instansi\InstansiController;
use App\Http\Controllers\Instansi\SubInstansiController;
use App\Http\Controllers\ArsipKolektor\ArsipKolektorController;
use App\Http\Controllers\ArsipKolektor\SurveyController;
use App\Http\Controllers\ArsipKolektor\JawabanSurveyController;
use App\Http\Controllers\ArsipKolektor\JenisArsipController;
use App\Http\Controllers\ArsipKolektor\InstrumenSurveyController;
use App\Http\Controllers\ArsipKolektor\ListArsipController;
use App\Http\Controllers\ArsipKolektor\ImportArsipController;
use App\Http\Controllers\ArsipIdentifikasi\ArsipIdentifikasiController;
use App\Http\Controllers\MasterDataKinerja\RealisasiAnggaranController;
use App\Http\Controllers\MasterDataKinerja\SasaranStrategisController;
use App\Http\Controllers\MasterDataKinerja\CapaianController;
use App\Http\Controllers\MasterDataKinerja\IndikatorKinerjaController;
use App\Http\Controllers\MasterDataKinerja\TargetKinerjaController;
use App\Http\Controllers\MasterDataKinerja\PeranStrategisController;
use App\Http\Controllers\MasterDataKinerja\TujuanController;
use App\Http\Controllers\MasterDataKinerja\RencanaStrategisController;
use App\Http\Controllers\MasterDataKinerja\PerjanjianKinerjaController;
use App\Http\Controllers\MasterDataKinerja\CapaianKinerjaController;
use App\Http\Controllers\MasterDataKinerja\VisiMisiController;
use App\Http\Controllers\MasterDataKinerja\TugasFungsiController;
use App\Http\Controllers\MasterDataKinerja\StrukturOrganisasiController;
use App\Http\Controllers\MasterDataKinerja\CapaianSPBEController;
use App\Http\Controllers\ModelKinerja\ModelKinerjaController;
use App\Http\Controllers\Metadata\MetaDataController;
use App\Http\Controllers\Metadata\GlosariumController;
use Illuminate\Support\Facades\Redirect;
use Laravel\Passport\ClientRepository;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Landing Page
Route::get('/', [LandingPageController::class, 'index'])->name('welcome');

// Protected XSS Route
Route::middleware(['XSS'])->group(function () {

    Route::get('/visi-misi', [LandingPageController::class, 'visimisi'])->name('visi-misi');
    
    Route::get('/tugas-fungsi', [LandingPageController::class, 'tugasfungsi'])->name('tugas-fungsi');
    
    Route::get('/struktur-organisasi', [LandingPageController::class, 'strukturorganisasi'])->name('struktur-organisasi');
    
    Route::get('/infografis', [LandingPageController::class, 'infografis'])->name('infografis');
    
    Route::get('/unit-kerja', [LandingPageController::class, 'unitkerja'])->name('unit-kerja');
    
    Route::get('/unit-kerja/detail/{id}', [LandingPageController::class, 'detailunitkerja'])->name('detail-unit-kerja');
    
    Route::get('/berita', [LandingPageController::class, 'news'])->name('news');
    
    Route::get('/berita/detail/{slug}', [LandingPageController::class, 'detailnews'])->name('detail-news');
    
    Route::get('/infografis/detail/{slug}', [LandingPageController::class, 'detailinfografis'])->name('detail-infografis');
    
    Route::post('getsubCategory', [LandingPageController::class, 'getsubCategory'])->name('getsubCategory');
    
    Route::post('getYear', [LandingPageController::class, 'getYear'])->name('getYear');
    
    Route::get('getKinerja', [LandingPageController::class, 'getKinerja'])->name('getKinerja');
    
    Route::post('search', [SearchController::class, 'search'])->name('search');

    Route::get('/capaian-spbe', [LandingPageController::class, 'capaianspbe'])->name('capaian-spbe');

    Route::get('/capaian-spbe/detail/{id}', [LandingPageController::class, 'detailcapaianspbe'])->name('detail-capaian-spbe');

    Route::get('/capaian-kinerja', [LandingPageController::class, 'capaianKinerja'])->name('capaian-kinerja');

    Route::get('/capaian-kinerja/detail/{id}', [LandingPageController::class, 'detailcapaianKinerja'])->name('detail-capaian-kinerja');

    Route::get('/capaian-lainnya', [LandingPageController::class, 'capaian'])->name('capaian-lainnya');

    Route::get('/capaian-lainnya/detail/{id}', [LandingPageController::class, 'detailcapaian'])->name('detail-capaian-lainnya');

    Route::get('/get-detail-arsip/{id}', [LandingPageController::class, 'getDetailArsip'])->name('get-detail-arsip');
});

// Authentication
Route::middleware(['revalidate','XSS'])->group(function () {
    Auth::routes([
        'register' => false,
        'verify' => true,
    ]); 
});

// Laravel File Manager
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::middleware(['auth', 'revalidate'])->group(function () {

    // Redirect to dashboard after login
    Route::get('/redirect', function () {

        //return redirect()->intended();
        if (auth()->user()->hasRole('admin') || auth()->user()->hasRole('super-admin')) {
            return Redirect::intended('Dashboard');
        } elseif (auth()->user()->hasRole('Eksekutif')) {
            return Redirect::intended('Informasi-Eksekutif');
        } else {
            return Redirect::intended('home');
        }

    });
    
    // Dashboard Admin 
    Route::prefix('Dashboard')->group(function () {

        // Dashboard Admin
        Route::get('/', [DashboardController::class, 'index'])->name('dashboard.admin');
        
        Route::get('/chart-user', [DashboardController::class, 'handlechartuser'])->name('dashboard.chart-user');
    });

    // Dashboard Informasi Eksekutif
    Route::prefix('Informasi-Eksekutif')->group(function () {

        Route::get('/', [DashboardController::class, 'eksekutif'])->name('dashboard.eksekutif');
    
    });

    // Arsip Kolektor
    Route::prefix('arsip-kolektor')->group(function () {

        Route::get('instrumen-survey' , [InstrumenSurveyController::class, 'index'])->name('instrumen-survey.index');
        
        Route::get('instrumen-survey/isi-survey/{id}' , [InstrumenSurveyController::class, 'create'])->name('instrumen-survey.isisurvey');

        Route::post('instrumen-survey/{id}' , [InstrumenSurveyController::class, 'store'])->name('instrumen-survey.store');

        Route::get('instrumen-survey/edit/{id}' , [InstrumenSurveyController::class, 'edit'])->name('instrumen-survey.edit');

        Route::post('instrumen-survey/update/{id}' , [InstrumenSurveyController::class, 'update'])->name('instrumen-survey.update');
        
        Route::get('import-arsip' , [ImportArsipController::class, 'index'])->name('import-arsip.index');

        Route::post('import-arsip/store', [ImportArsipController::class, 'store'])->name('import-arsip.store');
    
        Route::get('instrumen-survey/responden/{id}', [InstrumenSurveyController::class, 'listResponden'])->name('instrumen-survey.listresponden');

        Route::resource('list-arsip', ListArsipController::class); 

        Route::post('list-arsip-digital/upload/{id}', [ListArsipController::class, 'upload'])->name('list-arsip-digital.upload');
        Route::get('list-arsip-digital/list/{id}', [ListArsipController::class, 'list'])->name('list-arsip-digital.list');
        Route::get('list-arsip-digital/download/{id}', [ListArsipController::class, 'download'])->name('list-arsip-digital.download');
        Route::delete('list-arsip-digital/delete/{id}', [ListArsipController::class, 'delete'])->name('list-arsip-digital.delete');
        Route::delete('list-arsip-digital/hapus/{id}', [ListArsipController::class, 'deleteFile'])->name('list-arsip-digital.hapus');
    });

    Route::prefix('arsip-identifikasi')->group(function () {
        Route::resource('taxonomy', \App\Http\Controllers\ArsipIdentifikasi\TaxonomyController::class); 
        Route::resource('list-arsip-digital', \App\Http\Controllers\ArsipIdentifikasi\ListArsipDigitalController::class);
        Route::get('list-arsip-digital/download/{id}', [ListArsipController::class, 'download'])->name('list-arsip-digital.download');
    });

    Route::prefix('arsip')->group(function () {
        Route::resource('survey', SurveyController::class);
        // Arsip Kolektor
        Route::resource('arsip-kolektor', ArsipKolektorController::class);
        Route::resource('jenis-arsip', JenisArsipController::class);
        Route::post('isi-survey/{id}', [JawabanSurveyController::class, 'store'])->name('arsip.jawab-survey');

resources/views/home.blade.php
@extends('layouts.dashboard')

@section('title')
Dashboard
@endsection

@section('css')
    <style>
        .alert-bg-random{
            background-image: url(https://source.unsplash.com/featured/900x80);
        }
    </style>
@endsection

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Dashboard</h1>
    </div>
    <div class="section-body">
        <h2 class="section-title">Selamat Datang {{ auth()->user()->name }}</h2>
        <p class="section-lead">
            Anda login sebagai {{ auth()->user()->roles->first()->description }}
            @if (auth()->user()->workunit_id != null)
            dari Unit Kerja {{
        auth()->user()->workunit->name }}
            @elseif(auth()->user()->workunit_id == null && auth()->user()->instansi_id != null)
            dari Instansi {{ auth()->user()->instansi->nama_instansi }}
            @endif
        </p>
        <div class="row">
            <div class="col-12 mb-4">
                <div class="hero text-white hero-bg-image hero-bg-parallax" style="background-image: url('{{ asset('admin/stisla/assets/img/unsplash/andre-benz-1214056-unsplash.jpg') }}');">
                    <div class="hero-inner">
                        <h2>Selamat Datang , {{ auth()->user()->name }}!</h2>
                        <p class="lead">
                            Anda login sebagai {{ auth()->user()->roles->first()->description }}
                            @if (auth()->user()->workunit_id != null)
                            dari Unit Kerja {{
                auth()->user()->workunit->name }} <br>
                            Terima kasih anda telah membantu kami dalam mengumpulkan data unit kerja {{ auth()->user()->workunit->name
                }}
                            @elseif(auth()->user()->workunit_id == null && auth()->user()->instansi_id != null)
                            dari Instansi {{ auth()->user()->instansi->nama_instansi }}
                            @endif
                            <br>
                            ~ Pusat Data dan Informasi ~ <br>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        @can('Statistik Produsen Data')
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                <div class="card card-statistic-1">
                    <div class="card-icon bg-primary">
                        <i class="fas fa-database"></i>
                    </div>
                    <div class="card-wrap">
                        <div class="card-header">
                            <h4>Data Terkumpul</h4>
                        </div>
                        <div class="card-body">
                            @php
                            $dataterkumpul = DB::table('kinerja')->where('produsendata_id',
                            auth()->user()->id)->where('workunit_id',
                            auth()->user()->workunit_id)->get()->groupBy(['category_id', 'year']);
                            @endphp
                            {{ $dataterkumpul->count() }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                <div class="card card-statistic-1">
                    <div class="card-icon bg-success">
                        <i class="fas fa-check-double"></i>
                    </div>
                    <div class="card-wrap">
                        <div class="card-header">
                            <h4>Data Terverifikasi</h4>
                        </div>
                        <div class="card-body">
                            @php
                            $dataterverifikasi = DB::table('kinerja')->where('produsendata_id',
                            auth()->user()->id)->where('workunit_id',
                            auth()->user()->workunit_id)->where('status', 4)->get()->groupBy(['category_id', 'year']);
                            @endphp
                            {{ $dataterverifikasi->count() }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                <div class="card card-statistic-1">
                    <div class="card-icon bg-warning">
                        <i class="fas fa-history"></i>
                    </div>
                    <div class="card-wrap">
                        <div class="card-header">
                            <h4>Data Sedang Di Proses</h4>
                        </div>
                        <div class="card-body">
                            @php
                            $datasedangproses = DB::table('kinerja')->where('produsendata_id',
                            auth()->user()->id)->where('workunit_id',
                            auth()->user()->workunit_id)->where('status', 3)->get()->groupBy(['category_id', 'year']);
                            @endphp
                            {{ $dataterverifikasi->count() }}
                            {{-- {{ \DB::table('kinerja')->where('produsendata_id', auth()->user()->id)->where('workunit_id',
                auth()->user()->workunit_id)->where('status', 4)->count() }} --}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                <div class="card card-statistic-1">
                    <div class="card-icon bg-info">
                        <i class="fas fa-clipboard-list"></i>
                    </div>
                    <div class="card-wrap">
                        <div class="card-header">
                            <h4>Aktivitas Input Data</h4>
                        </div>
                        <div class="card-body">
                            <div class="progress mt-3" style="height: 12px; border-radius: 50px">
                                @php
                                if(\DB::table('kinerja')->where('produsendata_id', auth()->user()->id)->where('workunit_id',
                                auth()->user()->workunit_id)->count() > 0){
                                $total = \DB::table('kinerja')->where('produsendata_id', auth()->user()->id)->where('workunit_id',
                                auth()->user()->workunit_id)->count() / \DB::table('kinerja')->where('workunit_id',
                                auth()->user()->workunit_id)->count() * 100;
                                } else {
                                $total = 0;
                                }
                                @endphp
                                <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" data-width="{{ $total }}%" aria-valuenow="{{ $total }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ $total }}%;">{{
                    $total }}%</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @endcan

        @can('Statistik Master Data')
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                    <div class="card card-statistic-1">
                        <div class="card-icon bg-success">
                            <i class="fas fa-users"></i>
                        </div>
                        <div class="card-wrap">
                            <div class="card-header">
                                <h4>Total Penugasan</h4>
                            </div>
                            <div class="card-body">
                                @php
                                $data = \DB::table('kinerja')
                                ->where('status', 3)
                                ->where('masterdata_id', auth()->user()->id)
                                ->get()->groupBy(['category_id', 'year']);
                                @endphp
                                {{ $data->count() }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                    <div class="card card-statistic-1">
                        <div class="card-icon bg-warning">
                            <i class="fas fa-history"></i>
                        </div>
                        <div class="card-wrap">
                            <div class="card-header">
                                <h4>Total Pending Penugasan</h4>
                            </div>
                            <div class="card-body">
                                @php
                                $data = \DB::table('kinerja')
                                ->where('status', 2)
                                ->get()->groupBy(['category_id', 'year']);
                                @endphp
                                {{ $data->count() }}
                            </div>
                        </div>
                    </div>
                </div>
        </div>
        @endcan

    @can('Statistik Pengolah Data')
    <div class="row">
        <div class="col-lg-4 col-md-6 col-sm-6 col-12">
            <div class="card card-statistic-1">
                <div class="card-icon bg-success">
                    <i class="fas fa-users"></i>
                </div>
                <div class="card-wrap">
                    <div class="card-header">
                        <h4>Total Penugasan</h4>
                    </div>
                    <div class="card-body">
                        @php
                        $data = \DB::table('kinerja')
                        ->where('status', 4)
                        ->where('pengolahdata_id', auth()->user()->id)
                        ->get()->groupBy(['category_id', 'year']);
                        @endphp
                        {{ $data->count() }}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-6 col-12">
            <div class="card card-statistic-1">
                <div class="card-icon bg-warning">
                    <i class="fas fa-history"></i>
                </div>
                <div class="card-wrap">
                    <div class="card-header">
                        <h4>Total Pending Penugasan</h4>
                    </div>
                    <div class="card-body">
                        @php
                        $data = \DB::table('kinerja')
                        ->where('status', 3)
                        ->where('pengolahdata_id', auth()->user()->id)
                        ->get()->groupBy(['category_id', 'year']);
                        @endphp
                        {{ $data->count() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endcan

    @if (auth()->user()->phone == null)
    <div class="row">
        <div class="col-12 mb-4">
            <div class="alert alert-danger alert-has-icon alert-dismissible show fade">
                <div class="alert-icon"><i class="fas fa-exclamation-triangle"></i></div>
                <div class="alert-body">
                    <button class="close" data-dismiss="alert">
                        <span>&times;</span>
                    </button>
                    <div class="alert-title">Perhatian !</div>
                    <p class="mb-0">
                        Silahkan Lengkapi Data Diri Anda Terlebih Dahulu Sebelum Melakukan Pengisian Data
                    </p>
                    <a href="{{ route('user.profile') }}" class="btn btn-outline-light mt-3 btn-lg btn-icon icon-left"><i class="fas fa-pen"></i> Lengkapi Data Diri</a>
                </div>
            </div>
        </div>
    </div>
    @endif

    @if (auth()->user()->roles->first()->name == 'Instansi')
        @foreach ($survey as $sy)
            <div class="row">
                <div class="col-12 mb-4">
                    <div class="hero text-white hero-bg-image hero-bg-parallax" style="background-image: url(https://source.unsplash.com/featured/900x201);">
                        <div class="hero-inner">
                            <h2>
                                Perhatian!
                            </h2>
                            <p class="lead text-capitalize">
                                Terdapat Instrumen Survey Baru Yang Harus Anda Isi, Dengan Judul {{ $sy->nama }} Tahun {{ $sy->tahun }} <br>
                                Silahkan Klik Tombol Dibawah Ini Untuk Melakukan Pengisian
                            </p>
                            <div class="mt-4">
                                <a href="{{ route('arsip-kolektor.show', Crypt::encrypt($sy->id)) }}" class="btn btn-outline-white btn-lg btn-icon icon-left"><i class="fas fa-pen"></i> Isi Survey</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    @endif
    </div>
</section>
@endsection

@section('js')

@endsection